// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {p2p} from '../models';

export function ConnectToNode(arg1:string,arg2:string):Promise<void>;

export function OnFrontendLoad():Promise<p2p.HostData>;
