// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles() {
  return window['go']['main']['App']['AddFiles']();
}

export function ConnectToNode(arg1, arg2) {
  return window['go']['main']['App']['ConnectToNode'](arg1, arg2);
}

export function GetPeerSharedFiles(arg1) {
  return window['go']['main']['App']['GetPeerSharedFiles'](arg1);
}

export function OnFrontendLoad() {
  return window['go']['main']['App']['OnFrontendLoad']();
}
